package(default_visibility = ["//visibility:public"])

cc_library(
    name = "foo",
    hdrs = ["foo.h"],
    deps = [
    ],
)

cc_binary(
    name = "mainfoo",
    srcs = ["mainfoo.cpp"],
    deps = [
        "@boost//:coroutine2",
    ],
)
